/**
 * Kahade — domain `referral` (kode undangan, riwayat, reward).
 */
import { http } from "@/lib/api/client"
import type { ApplyReferralDto } from "@/lib/api/types"

export type ReferralCode = {
  code: string
  createdAt?: string
  /** Salinan dibuat otomatis? */
  autoGenerated?: boolean
}

export type ReferralStats = {
  totalInvited: number
  completed: number
  pending: number
  totalReward: number
}

export type ReferralReward = {
  id: string
  code: string
  amount: number
  status: string
  createdAt: string
}

export type ReferralHistoryEntry = {
  id: string
  invitedUsername: string
  status: string
  reward?: number
  completedAt?: string | null
  createdAt: string
}

export function getMyReferralCode() {
  return http.get<ReferralCode>("/v1/referral/my-code", { auth: "required", retry: 1 })
}

export function regenerateReferralCode() {
  return http.post<ReferralCode>("/v1/referral/regenerate", undefined, { auth: "required" })
}

export function getReferralStats() {
  return http.get<ReferralStats>("/v1/referral/stats", { auth: "required", retry: 1 })
}

export function getReferralRewards() {
  return http.get<ReferralReward[]>("/v1/referral/rewards", { auth: "required", retry: 1 })
}

export function getReferralHistory() {
  return http.get<ReferralHistoryEntry[]>("/v1/referral/history", { auth: "required", retry: 1 })
}

export function applyReferralCode(dto: ApplyReferralDto) {
  return http.post<ReferralCode, ApplyReferralDto>("/v1/referral/apply", dto, { auth: "required" })
}

