/**
 * Stub `phosphor-react-native` untuk Vitest (config komponen) — DIBUAT
 * OTOMATIS dari daftar nama ikon yang diimpor seluruh source app/components/
 * lib. Ikon dirender sebagai <span data-icon> tanpa SVG: test komponen
 * mengunci teks & perilaku, bukan glyph. Bila source menambah ikon baru dan
 * test gagal dengan "does not provide an export named X", jalankan ulang
 * generator (lihat komentar generator di tests/stubs/README) atau tambahkan
 * namanya ke daftar di bawah.
 */
import React from "react"

function stub(name: string) {
  const Icon = (props: Record<string, unknown>) =>
    React.createElement("span", { "data-icon": name, ...pickDom(props) })
  Icon.displayName = name
  return Icon
}

function pickDom(props: Record<string, unknown>) {
  const out: Record<string, unknown> = {}
  if (props.testID) out["data-testid"] = props.testID
  if (props.accessibilityLabel) out["aria-label"] = props.accessibilityLabel
  return out
}


export const AppleLogo = stub("AppleLogo")
export const Archive = stub("Archive")
export const ArrowCircleDown = stub("ArrowCircleDown")
export const ArrowCircleUp = stub("ArrowCircleUp")
export const ArrowClockwise = stub("ArrowClockwise")
export const ArrowCounterClockwise = stub("ArrowCounterClockwise")
export const ArrowDown = stub("ArrowDown")
export const ArrowDownRight = stub("ArrowDownRight")
export const ArrowLeft = stub("ArrowLeft")
export const ArrowRight = stub("ArrowRight")
export const ArrowSquareOut = stub("ArrowSquareOut")
export const ArrowUUpLeft = stub("ArrowUUpLeft")
export const ArrowUp = stub("ArrowUp")
export const ArrowUpRight = stub("ArrowUpRight")
export const ArrowsClockwise = stub("ArrowsClockwise")
export const ArrowsLeftRight = stub("ArrowsLeftRight")
export const Article = stub("Article")
export const At = stub("At")
export const Backspace = stub("Backspace")
export const Bank = stub("Bank")
export const Bell = stub("Bell")
export const BellSlash = stub("BellSlash")
export const BellZ = stub("BellZ")
export const Bookmark = stub("Bookmark")
export const BookmarkSimple = stub("BookmarkSimple")
export const Briefcase = stub("Briefcase")
export const Broom = stub("Broom")
export const Buildings = stub("Buildings")
export const CalendarBlank = stub("CalendarBlank")
export const CalendarCheck = stub("CalendarCheck")
export const Camera = stub("Camera")
export const CardsThree = stub("CardsThree")
export const CaretDown = stub("CaretDown")
export const CaretLeft = stub("CaretLeft")
export const CaretRight = stub("CaretRight")
export const ChartLine = stub("ChartLine")
export const ChartLineUp = stub("ChartLineUp")
export const ChatCircle = stub("ChatCircle")
export const ChatCircleDots = stub("ChatCircleDots")
export const ChatCircleText = stub("ChatCircleText")
export const ChatTeardropDots = stub("ChatTeardropDots")
export const ChatText = stub("ChatText")
export const Chats = stub("Chats")
export const Check = stub("Check")
export const CheckCircle = stub("CheckCircle")
export const CheckSquare = stub("CheckSquare")
export const Checks = stub("Checks")
export const Circle = stub("Circle")
export const Clock = stub("Clock")
export const ClockCounterClockwise = stub("ClockCounterClockwise")
export const Coins = stub("Coins")
export const Compass = stub("Compass")
export const Copy = stub("Copy")
export const CreditCard = stub("CreditCard")
export const Crown = stub("Crown")
export const CrownSimple = stub("CrownSimple")
export const Desktop = stub("Desktop")
export const DeviceMobile = stub("DeviceMobile")
export const DeviceTablet = stub("DeviceTablet")
export const DotsThree = stub("DotsThree")
export const DotsThreeVertical = stub("DotsThreeVertical")
export const DownloadSimple = stub("DownloadSimple")
export const Envelope = stub("Envelope")
export const EnvelopeSimple = stub("EnvelopeSimple")
export const Eraser = stub("Eraser")
export const Export = stub("Export")
export const Eye = stub("Eye")
export const EyeSlash = stub("EyeSlash")
export const FacebookLogo = stub("FacebookLogo")
export const File = stub("File")
export const FileArchive = stub("FileArchive")
export const FileArrowDown = stub("FileArrowDown")
export const FileCsv = stub("FileCsv")
export const FilePdf = stub("FilePdf")
export const FileText = stub("FileText")
export const Fingerprint = stub("Fingerprint")
export const Flag = stub("Flag")
export const FunnelSimple = stub("FunnelSimple")
export const Gear = stub("Gear")
export const Gift = stub("Gift")
export const Globe = stub("Globe")
export const GlobeSimple = stub("GlobeSimple")
export const GooglePlayLogo = stub("GooglePlayLogo")
export const Handshake = stub("Handshake")
export const Headset = stub("Headset")
export const Heart = stub("Heart")
export const HeartStraight = stub("HeartStraight")
export const House = stub("House")
export const IconProps = stub("IconProps")
export const IconWeight = stub("IconWeight")
export const IdentificationBadge = stub("IdentificationBadge")
export const IdentificationCard = stub("IdentificationCard")
export const Image = stub("Image")
export const ImageBroken = stub("ImageBroken")
export const Images = stub("Images")
export const ImagesSquare = stub("ImagesSquare")
export const Info = stub("Info")
export const InstagramLogo = stub("InstagramLogo")
export const Key = stub("Key")
export const Laptop = stub("Laptop")
export const Lifebuoy = stub("Lifebuoy")
export const Lightning = stub("Lightning")
export const LinkSimple = stub("LinkSimple")
export const LinkedinLogo = stub("LinkedinLogo")
export const Lock = stub("Lock")
export const LockKey = stub("LockKey")
export const LockKeyOpen = stub("LockKeyOpen")
export const MagnifyingGlass = stub("MagnifyingGlass")
export const Mailbox = stub("Mailbox")
export const Medal = stub("Medal")
export const Megaphone = stub("Megaphone")
export const Microphone = stub("Microphone")
export const MicrophoneSlash = stub("MicrophoneSlash")
export const Minus = stub("Minus")
export const Moon = stub("Moon")
export const NotePencil = stub("NotePencil")
export const Package = stub("Package")
export const PaperPlaneRight = stub("PaperPlaneRight")
export const PaperPlaneTilt = stub("PaperPlaneTilt")
export const Paperclip = stub("Paperclip")
export const Password = stub("Password")
export const PencilSimple = stub("PencilSimple")
export const PencilSimpleLine = stub("PencilSimpleLine")
export const Percent = stub("Percent")
export const Phone = stub("Phone")
export const PhoneDisconnect = stub("PhoneDisconnect")
export const PhoneSlash = stub("PhoneSlash")
export const PhoneX = stub("PhoneX")
export const Plus = stub("Plus")
export const Printer = stub("Printer")
export const Prohibit = stub("Prohibit")
export const PushPin = stub("PushPin")
export const QrCode = stub("QrCode")
export const Question = stub("Question")
export const Receipt = stub("Receipt")
export const Scales = stub("Scales")
export const ScanSmiley = stub("ScanSmiley")
export const SealCheck = stub("SealCheck")
export const SealWarning = stub("SealWarning")
export const ShareNetwork = stub("ShareNetwork")
export const Shield = stub("Shield")
export const ShieldCheck = stub("ShieldCheck")
export const ShieldSlash = stub("ShieldSlash")
export const ShieldStar = stub("ShieldStar")
export const ShieldWarning = stub("ShieldWarning")
export const ShoppingBag = stub("ShoppingBag")
export const SignIn = stub("SignIn")
export const SignOut = stub("SignOut")
export const Smiley = stub("Smiley")
export const Sparkle = stub("Sparkle")
export const SpeakerHigh = stub("SpeakerHigh")
export const SpeakerSlash = stub("SpeakerSlash")
export const Star = stub("Star")
export const Storefront = stub("Storefront")
export const Sun = stub("Sun")
export const Tag = stub("Tag")
export const TelegramLogo = stub("TelegramLogo")
export const ThumbsUp = stub("ThumbsUp")
export const Ticket = stub("Ticket")
export const TiktokLogo = stub("TiktokLogo")
export const Timer = stub("Timer")
export const Translate = stub("Translate")
export const Trash = stub("Trash")
export const TrendUp = stub("TrendUp")
export const Truck = stub("Truck")
export const UploadSimple = stub("UploadSimple")
export const User = stub("User")
export const UserCircle = stub("UserCircle")
export const UserCircleMinus = stub("UserCircleMinus")
export const UserFocus = stub("UserFocus")
export const UserMinus = stub("UserMinus")
export const UserPlus = stub("UserPlus")
export const UserSwitch = stub("UserSwitch")
export const Users = stub("Users")
export const UsersThree = stub("UsersThree")
export const VideoCamera = stub("VideoCamera")
export const VideoCameraSlash = stub("VideoCameraSlash")
export const Wallet = stub("Wallet")
export const Warning = stub("Warning")
export const WarningCircle = stub("WarningCircle")
export const WhatsappLogo = stub("WhatsappLogo")
export const Wrench = stub("Wrench")
export const X = stub("X")
export const XCircle = stub("XCircle")
export const XLogo = stub("XLogo")
export const YoutubeLogo = stub("YoutubeLogo")

export default new Proxy({} as Record<string, unknown>, { get: (_t, p) => stub(String(p)) })
